---
records:
- key: site.heading
  klass: StringSetting
  value: Appleseed
  options: { validate_presence: true }
- key: site.subheading
  klass: StringSetting
  value: Greatness Sprouts From Little Seeds
- key: site.title
  klass: StringSetting
  value: Appleseed CMS
  options: { validate_presence: true }
- key: site.navigation
  klass: NavigationListSetting
  list:
    items:
      - label: Home
        url: '/'
      - label: Weapons
        url: '/weapons'
      - label: Potent Potables
        url: '/potent-potables'
