---
records:
- key: site.heading
  klass: StringSetting
  value: Appleseed
  validate_presence: true
- key: site.subheading
  klass: StringSetting
  value: Greatness Sprouts From Little Seeds
- key: site.title
  klass: StringSetting
  value: Appleseed CMS
  validate_presence: true
